# Generated by Django 4.1.5 on 2023-01-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cast_rename_movies_movie_rename_writers_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='casts',
            field=models.ManyToManyField(to='api.cast'),
        ),
    ]
