# Generated by Django 4.1.5 on 2023-01-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number_list',
        ),
    ]
